# risks:
  - risk_id: "T-O-RAN-01"
    workload: 
    - "CU"
    - "DU"
    risk_description: "Unauthenticated/unauthorized access of the O_RAN component leads to compromised performance and/or function/service, lateral attack towards other O-RAN system component(s) from inside, and loss/stolen/tampering of sensitive data"
    severity: "High"
    checkpoints:
      CHK_TLS:
        - description: "Is TLS Enabled?"
        - status: false
      CHK_POLP_INGRESS:
        - description: "Network Policies for Ingress connections?"
        - status: false
      CHK_SENSITIVE_ASSETS:
        - description: "Are Least Permissive Policies enforced for Sensitive Assets?"  
        - status: false  
  
  - risk_id: "T-O-RAN-01(NEAR RT RIC)"
    workload: 
     - "xApps"
     - "rApps"
    risk_description: "Unauthenticated/unauthorized access of the O_RAN component leads to compromised performance and/or function/service, lateral attack towards other O-RAN system component(s) from inside, and loss/stolen/tampering of sensitive data"
    severity: "High"
    checkpoints:
      CHK_TLS:
        - description: "Is TLS Enabled?"
        - status: false
      CHK_POLP_INGRESS:
        - description: "Network Policies for Ingress connections?"
        - status: false
      CHK_SENSITIVE_ASSETS:
        - description: "Are Least Permissive Policies enforced for Sensitive Assets?"  
        - status: false
  
  - risk_id: "3GPP-5GCore (Section 4.2.5)"
    workload: 
     - "UDR"
    risk_description: "Only UDM, PCF, and NEF can connect to Ingress on UDR"
    severity: "High"
    checkpoints:
      CHK_TLS:
        - description: "Is TLS Enabled?"
        - status: false
      CHK_POLP_INGRESS:
        - description: "Network Policies for Ingress connections?"
        - status: false
      CHK_SENSITIVE_ASSETS:
        - description: "Are Least Permissive Policies enforced for Sensitive Assets?"  
        - status: false

  - risk_id: "3GPP 33.501"
    workload: 
     - "NRF"
    risk_description: "No Egress connections should be allowed from NRF at runtime."
    severity: "High"
    checkpoints:
      CHK_TLS:
        - description: "Is TLS Enabled?"
        - status: false
      CHK_POLP_INGRESS:
        - description: "Network Policies for Ingress connections?"
        - status: false
      CHK_SENSITIVE_ASSETS:
        - description: "Are Least Permissive Policies enforced for Sensitive Assets?"   
        - status: false
  
  - risk_id: "MITRE-5GCORE"
    workload:
      - "SMF"
    risk_description: "There should be only one EGRESS connection i.e to UPF from SMF"
    severity: "High"
    checkpoints:
      CHK_TLS:
        - description: "Is TLS Enabled?"
        - status: false
      CHK_POLP_EGRESS:
        - description: "Network Policies for Ingress connections?"
        - status: false
      CHK_SENSITIVE_ASSETS:
        - description: "Are Least Permissive Policies enforced for Sensitive Assets?"   
        - status: false    
  